version: '3.7'

services:
  api:
    container_name: api
    image: node:12-stretch
    networks:
      - devnet
    ports:
      - 9000:9000
    volumes:
        - /code/node_modules
        - ./api:/code

    command: bash -c "cd /code && npm install && sleep infinity"
  mongo:
    container_name: mongo
    image: mongo:3.6.3
    networks:
      devnet:
        aliases: 
          - mongo
    ports:
      - 27017:27017
networks:
  devnet:
    name: devnet